### PR TITLE
第一周作業

### PR DESCRIPTION
**Pull request by ysirene**
老師好，我是李亞珊，我想繳交第一周的作業！
以下是測試的網址：
http://54.189.199.86:3000/api/attractions?page=1
http://54.189.199.86:3000/api/attractions?page=0&keyword=劍潭
http://54.189.199.86:3000/api/attractions?page=0&keyword=北
http://54.189.199.86:3000/api/attraction/10
http://54.189.199.86:3000/api/mrts

### CODE REVIEW

**Comment by cwpeng** [comment]
Request review explicitly in this pull request so that I can review for you.

**Comment by ysirene** [comment]
設定好了，不好意思！！

**Review by cwpeng — CHANGES_REQUESTED** [review]
Result is OK. But we cannot get all data at once and slice it by our own code. We should use SQL feature to do pagination.

Fix this issue and re-request review.

**Comment by ysirene** [comment]
修正好分頁的方式了，感謝老師提點

**Comment by cwpeng** [comment]
Re-request review from top right corner in this page so that I can review for you.

**Review by cwpeng — APPROVED** [review]
Good. Done.

**Comment by ysirene** [comment]
謝謝老師！

**Pull request merged**
